include Makefile

all: esp-test

SERIAL_PORT = /dev/tty.SLAB_USBtoUART
ESPIDF = $(realpath libs/esp-idf)

SUB_MAKE_ARGS += ESPIDF=$(ESPIDF) PORT=$(SERIAL_PORT) PROJECT_TOP=$(CURDIR) BOARD=GENERIC_OTA \
					MICROPY_SSL_MBEDTLS=1 MICROPY_SSL_AXTLS=0
# -j 4 BUILD_VERBOSE=1

esp-test:
	cd $(MPY_TOP)/ports/esp32 && $(MAKE) $(SUB_MAKE_ARGS)

esp-clean:
	cd $(MPY_TOP)/ports/esp32 && $(MAKE) $(SUB_MAKE_ARGS) clean

esp-deploy:
	cd $(MPY_TOP)/ports/esp32 && $(MAKE) $(SUB_MAKE_ARGS) deploy

