//
// random - cryptographic random number generation
//
// Cifra Hash_DRBG is seeded from the target entropy source. Generated bytes
// are also XORed with fresh source words after basic source-failure checks.
//
#include "py/runtime.h"
#include "py/mperrno.h"
#include "my_assert.h"
#include "cifra/drbg.h"
#include "cifra/ext/handy.h"
#include "random_backend.h"

static cf_hash_drbg_sha256 drbg;
static bool drbg_ready;
static uint32_t last_chip;

#define DRBG_ENTROPY_WORDS 32

static bool checked_chip_trng_read(uint32_t *out)
{
    uint32_t chip;

    if(!chip_trng_read(&chip) || !chip || chip == last_chip) {
        return false;
    }
    last_chip = chip;
    *out = chip;
    return true;
}

static uint32_t checked_chip_trng(void)
{
    uint32_t chip;
    if(!checked_chip_trng_read(&chip)) {
        mp_raise_OSError(MP_EFAULT);
    }
    return chip;
}

static void drbg_seed_from_chip(void)
{
    uint32_t entropy[DRBG_ENTROPY_WORDS];
    for(int i = 0; i < DRBG_ENTROPY_WORDS; i++) {
        if(!checked_chip_trng_read(&entropy[i])) {
            mem_clean(entropy, sizeof entropy);
            mp_raise_OSError(MP_EFAULT);
        }
    }

    if(drbg_ready) {
        cf_hash_drbg_sha256_reseed(&drbg, entropy, sizeof(entropy), NULL, 0);
    } else {
        static const char domain[] = "libngu.random";
        cf_hash_drbg_sha256_init(&drbg, entropy, sizeof(entropy),
                                 NULL, 0, domain, sizeof(domain)-1);
        drbg_ready = true;
    }
    mem_clean(entropy, sizeof entropy);
}

static void drbg_setup(const void *seed, size_t seed_len)
{
    if(!drbg_ready) {
        drbg_seed_from_chip();
    }

    if(seed_len) {
        cf_hash_drbg_sha256_reseed(&drbg, seed, seed_len, NULL, 0);
    }
}

void my_random_bytes(uint8_t *dest, uint32_t count)
{
    if(!drbg_ready) {
        drbg_setup(NULL, 0);
    }
    if(cf_hash_drbg_sha256_needs_reseed(&drbg)) {
        drbg_seed_from_chip();
    }
    cf_hash_drbg_sha256_gen(&drbg, dest, count);

    while(count) {
        uint32_t chip = checked_chip_trng();

        int here = MIN(4, count);
        for(int i = 0; i < here; i++) {
            dest[i] ^= ((uint8_t *)&chip)[i];
        }
        dest += here;
        count -= here;
    }
}

STATIC mp_obj_t random_uint32(void) {
    // full 32-bit values, not 30
    uint32_t rv;
    my_random_bytes((uint8_t *)&rv, sizeof(rv));

    return mp_obj_new_int_from_uint(rv);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(random_uint32_obj, random_uint32);

int _bit_length(uint32_t x)
{
    if(!x) return 0;

    int bits = 1;
    while(x >> bits) {
        bits += 1;
    }
    return bits;
}

int _rand_below(int mx)
{
    if(mx <= 1) return 0;

    int bl = _bit_length(mx - 1);
    assert(bl && (bl < 31));

    uint32_t mask = (1u << bl) - 1;

    while(1) {
        uint32_t pt;
        my_random_bytes((uint8_t *)&pt, sizeof(pt));
        int rv = (int)(pt & mask);
        if(rv < mx) {
            return rv;
        }
    }
}

STATIC mp_obj_t random_uniform(mp_obj_t mx_in) {
    int mx = mp_obj_get_int_truncated(mx_in);

    return mp_obj_new_int_from_uint(_rand_below(mx));
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(random_uniform_obj, random_uniform);


STATIC mp_obj_t random_bytes(mp_obj_t count_in)
{
    int count = mp_obj_get_int_truncated(count_in);
    if(count < 0 || count > 4096) {
        mp_raise_ValueError(MP_ERROR_TEXT("out of range"));
    }

    vstr_t rv;
    vstr_init_len(&rv, count);

    my_random_bytes((uint8_t *)rv.buf, count);

    return mp_obj_new_str_from_vstr(&mp_type_bytes, &rv);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(random_bytes_obj, random_bytes);


STATIC mp_obj_t random_reseed(mp_obj_t arg)
{
    mp_buffer_info_t seed;
    mp_get_buffer_raise(arg, &seed, MP_BUFFER_READ);
    if(seed.len < 32) {
        mp_raise_ValueError(MP_ERROR_TEXT("seed too short"));
    }

    drbg_setup(seed.buf, seed.len);

    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(random_reseed_obj, random_reseed);


STATIC const mp_rom_map_elem_t globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_random) },

    { MP_ROM_QSTR(MP_QSTR_bytes), MP_ROM_PTR(&random_bytes_obj) },
    { MP_ROM_QSTR(MP_QSTR_uint32), MP_ROM_PTR(&random_uint32_obj) },
    { MP_ROM_QSTR(MP_QSTR_uniform), MP_ROM_PTR(&random_uniform_obj) },
    { MP_ROM_QSTR(MP_QSTR_reseed), MP_ROM_PTR(&random_reseed_obj) },
};

STATIC MP_DEFINE_CONST_DICT(globals_table_obj, globals_table);

const mp_obj_module_t mp_module_random = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t *)&globals_table_obj,
};
